name = "thynra"
compatibility_date = "2025-10-15"
main = "worker.js"

[assets]
directory = "./dist/public"

# Environment variables
[vars]
NODE_ENV = "development"

# Secrets (set these with: wrangler secret put SECRET_NAME)
# PAYPAL_CLIENT_ID = "your_paypal_client_id"
# PAYPAL_CLIENT_SECRET = "your_paypal_client_secret"

# Observability settings
[observability.logs]
enabled = false
head_sampling_rate = 1
invocation_logs = true
persist = true
