name = "thynra"
compatibility_date = "2025-10-15"
main = "worker.js"

[assets]
directory = "./dist/public"

[[routes]]
pattern = "thynra.com"
custom_domain = true

# Environment variables (you'll need to set these in Cloudflare dashboard)
[vars]
NODE_ENV = "production"
